### ISSUE TITLE
Latest version incompatible with latest (patch) version of TET Client SDK

### ISSUE THREAD

**Issue by ragset** [EyeTribe/tet-wpf-controls#2]
As the title states, the latest version (0.99.77) has a strict (= 0.9.77) [TET Client SDK](https://github.com/EyeTribe/tet-csharp-client) version dependence. I might very well be wrong (as the SDK is not using semantic versioning) but I would consider this an issue as patch version-bumps should not affect depending libs.

Best Regards
Ragnar

**Comment by metinsenturk** [comment]
I am also getting this error. I think this might happen due to the Newtonsoft.Json library versions. TetClient SDK is using the latest version of Newtonsoft. Updating newtonsoft library might work this out.

UPDATE: Tested, not b/c of Newtonsoft.Json library.

UPDATE2: I updated client SDK, everything works out perfectly.

**Comment by Hskovsgaard** [comment]
I believe our latest update fixed the issue that you experienced. The latest version updates to latest version of the SDK and JSON lib.

**Comment by ragset** [comment]
Thank you!
